name: Snake Game Animation

on:
  schedule:
    - cron: "0 12 * * *"  # Executa todos os dias às 20:00 UTC
  workflow_dispatch:      # Permite executar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: lordrodrigoo  # Substitua pelo seu username do GitHub
          outputs: dist/snake.svg

      - name: Upload Snake Game
        uses: actions/upload-artifact@v3
        with:
          name: snake-game
          path: dist/snake.svg
